baseURL = 'https://viniciusbaca.com/'
languageCode = 'en-us'
title = 'Vinícius Baca'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "my website for fun"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hey!'
homeIntroContent = """
I am a Brazilian/Peruvian software engineer based in Sao Paulo, passionate about hiking, 
travelling, and recently in triathlon training. \n
This is my personal website for fun, feel free to check my [trips](/trips) and my [cv](/cv).
"""

# Collection to display on home
homeCollectionTitle = 'trips'
homeCollection = 'trips'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2006 Jan 2'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/vinicius-baca/"

[[params.social]]
name = "github"
url = "https://github.com/viniciusbaca"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "trips"
url = "/trips"

[[params.menu]]
name = "cv"
url = "/cv"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"